### ISSUE TITLE
Unable to register secret with gh command

### ISSUE THREAD

**Issue by eitsupi** [r-hub/rhub2#19]
I think this is strictly a bug in the `gitcreds` package, but `rhub2` doesn't seem to recognize it even though I registered the secret in the GitHub CLI.

```sh
$ gh secret list
NAME   UPDATED            
RHUB2  about 3 minutes ago
```

```r
> rhub2::rhub_doctor()
✔ Found R package at /workspaces/httpgd.
✔ Found git repository at /workspaces/httpgd.
→ Do you have a GitHub personal access token (PAT)?
```

This hangs:

```r
> gitcreds::gitcreds_get()
```

**Comment by gaborcsardi** [comment]
What OS and what credential helper?

**Comment by eitsupi** [comment]
> What OS and what credential helper?

I haven't set any credential helpers on Ubuntu 22.04 on the container.
Maybe I need to do something with environment variables? It wasn't clear to me. (In other words, I don't need to worry about anything as long as I use the `gh` command)

**Comment by gaborcsardi** [comment]
AFAIR gh just stores your token in a plain text file, and I suspect that it installs its own credential helper that does not work well with gitcreds, apparently.

So until this is fixed in gitcreds, a workaround is indeed to set the `GITHUB_PAT` env var.

**Comment by eitsupi** [comment]
Thanks, since I am working within VS Code Dev Containers, it appears that the credential helpers set up by VS Code Dev Containers are being used.

```sh
$ git config credential.helper
!f() { /home/user/.vscode-server/bin/1e790d77f81672c49be070e04474901747115651/node /tmp/vscode-remote-containers-dfcfcb41-7bf4-4916-bc63-9db9c9b00bfe.js git-credential-helper $*; }; f
```

(As a side note, I was wondering why installing packages on GitHub using `pak::pak()` causes a hang, perhaps this is the cause)

It turns out that `gh` has store credentials on `~/.config/gh/hosts.yml`. (cli/cli#7023)

```yml
github.com:
    users:
        eitsupi:
            oauth_token: gho_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    git_protocol: https
    oauth_token: gho_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    user: eitsupi
```
